services:
  frontend:
    image: zlianrong1224/portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend

  backend:
    image: nginx:stable-alpine
    container_name: portfolio-backend
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/main.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
