services:
  nginx:
    image: "${{secret.DOCKER_USERNAME}}/nginx:${{github.sha}}"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/main.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:5173"
