version: '3.8'

services:
  nginx:
    image: ${DOCKERHUB_USERNAME}/nginx:${GITHUB_SHA}
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/main.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:5173"
