name: Docker Compose Build and Push

on:
  push:
    branches:
      - main  # 更改為您的主分支名稱
  workflow_dispatch:  # 添加這一行以啟用手動觸發

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        run: |
          docker-compose build
          docker-compose push

      - name: Logout from Docker Hub
        run: docker logout

      - name: Trigger Jenkins jobs
        run: |
          Jenkins_URL="http://140.128.101.144:8090/job/your-job-name/build"
          Jenkins_User="talen"
          Jenkins_Token="11b18f66d5ca71c1d78661cfab63a13da6"
          curl -u $JENKINS_USER:$JENKINS_API_TOKEN -X POST $JENKINS_URL

  # deploy-to-server:
  #   name: Deploy to Server
  #   runs-on: ubuntu-latest
  #   needs: build-and-push  # 指定依賴的job

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Setup SSH key
  #       uses: webfactory/ssh-agent@v0.5.3
  #       with:
  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  #     - name: SSH to server
  #       run: |
  #         ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

  #     - name: Pull and run Docker image
  #       run: |
  #           "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${GITHUB_SHA} && \
  #            docker run -d -p 8000:5173 ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${GITHUB_SHA}"
