name: Docker Compose Build and Push

on:
  push:
    branches:
      - main  # 更改為您的主分支名稱

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        run: |
          docker build . -t zlianrong1224/portfolio:latest
          docker image push zlianrong1224/portfolio:latest

      - name: Logout from Docker Hub
        run: docker logout
      
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: http://140.128.101.144:8090
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: 'Deploy'
