name: Docker Compose Build and Push

on:
  push:
    branches:
      - main  # 更改為您的主分支名稱

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        run: |
          docker-compose build
          docker-compose push

      - name: Logout from Docker Hub
        run: docker logout

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx
          docker run -d -p 8000:5173 ${{ secrets.DOCKERHUB_USERNAME }}/nginx
